### ISSUE TITLE
HC-SR04 not working with 7.x

### ISSUE THREAD

**Issue by albowler** [adafruit/CircuitPython_Community_Bundle#104]
Hi,

The hcsr04 sonar sensor, and the RCWL-1601 (lower voltage compatible sonar sensor) - does not work with the 7.x versions of CircuitPython, only if you downgrade the chip (tried with gemma m0 and itsy bitsy m0) - 6.x version will the sensors work again.

6.3.0.uf2, and use the 6.x version of adafruit_hcsr04.mpy

Thank you!

**Comment by tekktrik** [comment]
@albowler I would create an issue in the repository for that driver so it can be worked on there:  https://github.com/mmabey/CircuitPython_HCSR04/tree/ad6afffa0fddd86984b183f9f1f1e2d569f77bf8

Closing since it can't be fixed from the bundle.
