### ISSUE TITLE
circup --verbose update --all fails to fetch the proper version of CircuitPython_Community_Bundle

### ISSUE THREAD

**Issue by NicolasMas** [adafruit/CircuitPython_Community_Bundle#182]
Not sure if this is to be reported as a **circup** or a **CircuitPython_Community_Bundle** issue.
MacOS Sonoma, Metro express M0, homebrew, circup and latest **CircuitPython 8.2.6.**
Command: `circup --verbose update --all`

From the release notes at [https://github.com/adafruit/CircuitPython_Community_Bundle/releases/tag/20231004](https://github.com/adafruit/CircuitPython_Community_Bundle/releases/tag/20231004) it should fetch the 8.x bundle instead of the 7.x.

`
....
10/04/2023 19:07:23 INFO: Checking library updates for adafruit/CircuitPython_Community_Bundle.
10/04/2023 19:07:23 INFO: Requesting redirect information: https://github.com/adafruit/CircuitPython_Community_Bundle/releases/latest
10/04/2023 19:07:23 INFO: Tag: '20231004'
10/04/2023 19:07:23 INFO: New version available (20231004).
Downloading latest version for adafruit/CircuitPython_Community_Bundle.
10/04/2023 19:07:23 INFO: Downloading bundle: https://github.com/adafruit/CircuitPython_Community_Bundle/releases/download/20231004/circuitpython-community-bundle-py-20231004.zip

10/04/2023 19:07:24 INFO: Saved to /Users/REDACTED/Library/Application Support/circup/circuitpython-community-bundle-py.zip
10/04/2023 19:07:24 INFO: Downloading bundle: https://github.com/adafruit/CircuitPython_Community_Bundle/releases/download/20231004/circuitpython-community-bundle-7.x-mpy-20231004.zip
10/04/2023 19:07:25 WARNING: Unable to connect to https://github.com/adafruit/CircuitPython_Community_Bundle/releases/download/20231004/circuitpython-community-bundle-7.x-mpy-20231004.zip
**There was a problem downloading the bundle. Please try again in a moment.
10/04/2023 19:07:25 ERROR: 404 Client Error: Not Found for url: https://github.com/adafruit/CircuitPython_Community_Bundle/releases/download/20231004/circuitpython-community-bundle-7.x-mpy-20231004.zip
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/circup/__init__.py", line 483, in ensure_latest_bundle
    get_bundle(bundle, tag)
  File "/opt/homebrew/lib/python3.11/site-packages/circup/__init__.py", line 702, in get_bundle
    r.raise_for_status()
  File "/opt/homebrew/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://github.com/adafruit/CircuitPython_Community_Bundle/releases/download/20231004/circuitpython-community-bundle-7.x-mpy-20231004.zip**
`

[circup-log.txt](https://github.com/adafruit/CircuitPython_Community_Bundle/files/12802665/circup-log.txt)

**Comment by rjauquet** [comment]
It looks like the 7.x is no longer published with the community bundle releases, there is only an 8.x. I'm running into a similar issue at the moment. https://github.com/adafruit/CircuitPython_Community_Bundle/releases/tag/20231004

**Comment by rjauquet** [comment]
Fixed in circup 1.2.4, thanks @dhalbert

**Comment by dhalbert** [comment]
Fixed by https://github.com/adafruit/circup/pull/177. Also needed to create an 8.x CircuitPython_Org bundle.
