### ISSUE TITLE
How is a community bundle library listed in the requirements.txt of another community bundle library?

### ISSUE THREAD

**Issue by CedarGroveStudios** [adafruit/CircuitPython_Community_Bundle#192]
The `cedargrove_chime` library depends on the `cedargrove_midi_tools` library. Both are in the Community Bundle. How should the requirement for midi-tools library be listed in the chime library's `requirements.txt`? The goal is to have the dependency recognized by `circup`.

**Comment by tekktrik** [comment]
@CedarGroveStudios based on what I'm reading, this can be closed now, right?

**Comment by CedarGroveStudios** [comment]
Yes, it can be closed.
