### ISSUE TITLE
Libraries List Page

### ISSUE THREAD

**Issue by askpatrickw** [adafruit/CircuitPython_Community_Bundle#67]
The Adafruit_CircuitPython_Bundle has a nice [list of all the libraries](https://github.com/adafruit/Adafruit_CircuitPython_Bundle/blob/master/circuitpython_library_list.md). 

- [x] The community bundle should have a similiar page.
- [x] Add a link to that page from [Awesome CP - Code](https://circuitpython.org/awesome#code)

**Comment by lesamouraipourpre** [comment]
The docs link in `README.md` goes to `https://circuitpython.readthedocs.io/en/latest/docs/drivers.html`
Should this be updated to a Community Bundle version as part of this update?

**Comment by jposada202020** [comment]
I added the community library to Awesome - CP- Code here https://github.com/adafruit/awesome-circuitpython/pull/30

**Comment by prcutler** [comment]
I think this can be closed - the community bundle library is here: https://github.com/adafruit/CircuitPython_Community_Bundle/blob/main/circuitpython_community_library_list.md and it is linked from the Awesome List

**Comment by askpatrickw** [comment]
I concur, thanks!
