### ISSUE TITLE
BetterPad: An easy-to-use wrapper over GamePadShift

### ISSUE THREAD

**Issue by GingerIndustries** [adafruit/CircuitPython_Community_Bundle#69]
GamePadShift is an essential component of some Adafruit boards (read: PyGamer), but is not very... beginner-friendly. BetterPad aims to fix that. It's a small wrapper over GamePadShift that makes it _far_ easier to use. It provides one class, BetterPad. This class takes the same parameters as a GamePadShift class, and has one function: getPressed. This function returns a dictionary in this format: {"a": True, "b": False, ...} where the value of each key corresponds to the state of the button it represents. You can also pass a dictionary as the buttons parameter to the constructor, for different gamepads. See the attached file for the source.
[betterpad.zip](https://github.com/adafruit/circuitpython/files/6330013/betterpad.zip)

**Comment by GingerIndustries** [comment]
I've added another feature: getPressed's return dict now includes a "none" key, which is True if all buttons are False. (For waiting until none are pressed)
[betterpad.zip](https://github.com/adafruit/CircuitPython_Community_Bundle/files/6330026/betterpad.zip)

**Comment by GingerIndustries** [comment]
it's now in a GitHub repo 
https://github.com/GingerIndustries/adafruit-betterpad

**Comment by jposada202020** [comment]
@GingerIndustries you can follow this guide to add it to the community library.
https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/sharing-in-the-community-bundle
Ping-me in discord if you need anything.

**Comment by jposada202020** [comment]
@GingerIndustries if you want this added to the Community bundle please submit a PR, for the time being I will close this issue, Still wiling to help you in the process to add this to the community bundle if that is the path that you want to take. Thanks
